In [1]:
import pandas as pd

In [2]:
survey = pd.read_csv('survey_results_public.csv')

In [3]:
survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
Respondent                88883 non-null int64
MainBranch                88331 non-null object
Hobbyist                  88883 non-null object
OpenSourcer               88883 non-null object
OpenSource                86842 non-null object
Employment                87181 non-null object
Country                   88751 non-null object
Student                   87014 non-null object
EdLevel                   86390 non-null object
UndergradMajor            75614 non-null object
EduOther                  84260 non-null object
OrgSize                   71791 non-null object
DevType                   81335 non-null object
YearsCode                 87938 non-null object
Age1stCode                87634 non-null object
YearsCodePro              74331 non-null object
CareerSat                 72847 non-null object
JobSat                    70988 non-null object
MgrIdiot                  61159 non-null object
MgrMoney                  61157 non-null object
MgrWant                   61232 non-null object
JobSeek                   80555 non-null object
LastHireDate              79854 non-null object
LastInt                   67155 non-null object
FizzBuzz                  71344 non-null object
JobFactors                79371 non-null object
ResumeUpdate              77877 non-null object
CurrencySymbol            71392 non-null object
CurrencyDesc              71392 non-null object
CompTotal                 55945 non-null float64
CompFreq                  63268 non-null object
ConvertedComp             55823 non-null float64
WorkWeekHrs               64503 non-null float64
WorkPlan                  68914 non-null object
WorkChallenge             68141 non-null object
WorkRemote                70284 non-null object
WorkLoc                   70055 non-null object
ImpSyn                    71779 non-null object
CodeRev                   70390 non-null object
CodeRevHrs                49790 non-null float64
UnitTests                 62668 non-null object
PurchaseHow               61108 non-null object
PurchaseWhat              62029 non-null object
LanguageWorkedWith        87569 non-null object
LanguageDesireNextYear    84088 non-null object
DatabaseWorkedWith        76026 non-null object
DatabaseDesireNextYear    69147 non-null object
PlatformWorkedWith        80714 non-null object
PlatformDesireNextYear    77443 non-null object
WebFrameWorkedWith        65022 non-null object
WebFrameDesireNextYear    62944 non-null object
MiscTechWorkedWith        59586 non-null object
MiscTechDesireNextYear    64511 non-null object
DevEnviron                87317 non-null object
OpSys                     87851 non-null object
Containers                85366 non-null object
BlockchainOrg             48175 non-null object
BlockchainIs              60165 non-null object
BetterLife                86269 non-null object
ITperson                  87141 non-null object
OffOn                     86663 non-null object
SocialMedia               84437 non-null object
Extraversion              87305 non-null object
ScreenName                80486 non-null object
SOVisit1st                83877 non-null object
SOVisitFreq               88263 non-null object
SOVisitTo                 88086 non-null object
SOFindAnswer              87816 non-null object
SOTimeSaved               86344 non-null object
SOHowMuchTime             68378 non-null object
SOAccount                 87828 non-null object
SOPartFreq                74692 non-null object
SOJobs                    88066 non-null object
EntTeams                  87841 non-null object
SOComm                    88131 non-null object
WelcomeChange             85855 non-null object
SONewContent              69560 non-null object
Age                       79210 non-null float64
Gender                    85406 non-null object
Trans                     83607 non-null object
Sexuality                 76147 non-null object
Ethnicity                 76668 non-null object
Dependents                83059 non-null object
SurveyLength              86984 non-null object
SurveyEase                87081 non-null object
dtypes: float64(5), int64(1), object(79)
memory usage: 57.6+ MB

In [5]:
survey.head(2)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult